var fname = "shubham";
var lname = "nigam";
var age = 22;
var maritalstatus = false;
var college = "RVCE";
var pincode = 560059;
var state = "karnataka";
var city = 'bengaluru';
console.log(fname);
console.log(lname);
console.log(age);
console.log(maritalstatus);
console.log(college);
console.log(pincode);
console.log(state);
console.log("" + city);
